version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: nexopeak-postgres
    environment:
      POSTGRES_DB: nexopeak
      POSTGRES_USER: nexopeak
      POSTGRES_PASSWORD: nexopeak123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nexopeak-network

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: nexopeak-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nexopeak-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexopeak-backend
    environment:
      - DATABASE_URL=postgresql://nexopeak:nexopeak123@postgres:5432/nexopeak
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here-change-in-production
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - nexopeak-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nexopeak-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - nexopeak-network
    command: npm run dev

  # Celery Worker
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexopeak-celery
    environment:
      - DATABASE_URL=postgresql://nexopeak:nexopeak123@postgres:5432/nexopeak
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
      - backend
    networks:
      - nexopeak-network
    command: celery -A app.core.celery worker --loglevel=info

  # Celery Beat (Scheduler)
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexopeak-celery-beat
    environment:
      - DATABASE_URL=postgresql://nexopeak:nexopeak123@postgres:5432/nexopeak
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
      - backend
    networks:
      - nexopeak-network
    command: celery -A app.core.celery beat --loglevel=info

volumes:
  postgres_data:
  redis_data:

networks:
  nexopeak-network:
    driver: bridge
